#!/usr/bin/env python 

import getpass
from monkey import repl

if __name__ == '__main__':
    user = getpass.getuser()
    print(f'Hello, {user}! This is the Monkey programming language!\n')
    repl.start()
